version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
      - ./gee-demeter-app.json:/app/cred.json
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python -m arq app.worker.WorkerSettings
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
      - ./gee-demeter-app.json:/app/cred.json
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
