FROM node:20-alpine as build-stage

WORKDIR /app

COPY frontend/package*.json ./frontend/
RUN cd frontend && npm install

COPY frontend/ ./frontend/

RUN cd frontend && npm run build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "'daemon off;"]
